services:
  api:
    build: 
      context: . 
    shm_size: "2gb"
    image: age-prediction-backend
    container_name: age_api_dev
    ports:
      - "8080:8080" # Optuna Dashboard
      - "6006:6006" # TensorBoard
      - "8000:8000" # FastAPI
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - MODEL_PATH=models/convnext_tiny_bs64_lr2.90e-04_wd1.02e-04_mae4.49.pth
    stdin_open: true
    tty: true
    working_dir: /app

  frontend:
    build:
      context: ./frontend 
    image: age-prediction-frontend
    container_name: age_front_dev
    ports:
      - "5173:5173" # Vite
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:8000